name: hauptstadtfilm
favicon: null
layout_spectrum: 0.3528089930769056
typography_spectrum: 0.22438600077293813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6773563572205603
  lightness: 0.7346127689816058
  saturation: 0.0943436820525676
  rhythmicContrast: 0.9690160136669874
purpose: []
