favicon: null
name: hauptstadtfilm
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#585f79'
    - '#fe50fe'
    - '#b92a24'
  lightness: 1
typography_spectrum: 0.4699248
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3528089930769056
analytics:
  twitter: null
  google: null
  facebook: null
