name: hauptstadtfilm
favicon: null
layout_spectrum: 0.3528089930769056
typography_spectrum: 0.22438600077293813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#585f79'
    - '#fe50fe'
    - '#b92a24'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
